config/routes.rb
Rails.application.routes.draw do
  resources :sections
  resources :random_exams
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/random_exam.rb
class RandomExam < ApplicationRecord
  has_many :random_exam_sections, inverse_of: :random_exam
  has_many :sections, :through => :random_exam_sections

  accepts_nested_attributes_for :random_exam_sections, reject_if: :is_not_selected


  private
  def is_not_selected(attr)
    attr["selected"] == '0'
  end
end

app/models/random_exam_section.rb
class RandomExamSection < ApplicationRecord
  belongs_to :random_exam
  belongs_to :section

  attr_accessor :selected
end

app/models/section.rb
class Section < ApplicationRecord
  has_many :random_exam_sections
  has_many :random_exams, :through => :random_exam_sections
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/random_exams_controller.rb
class RandomExamsController < ApplicationController
  before_action :set_random_exam, only: [:show, :edit, :update, :destroy]

  # GET /random_exams
  # GET /random_exams.json
  def index
    @random_exams = RandomExam.all
  end

  # GET /random_exams/1
  # GET /random_exams/1.json
  def show
  end

  # GET /random_exams/new
  def new
    @random_exam = RandomExam.new
    @random_exam.random_exam_sections.build(Section.all.map{|s| {section_id: s.id}})
  end

  # GET /random_exams/1/edit
  def edit
    @random_exam
      .random_exam_sections
      .build(
        Section.where.not(id: @random_exam.section_ids).map{|s| {section_id: s.id}}
      )
  end

  # POST /random_exams
  # POST /random_exams.json
  def create
    @random_exam = RandomExam.new(random_exam_params)

    respond_to do |format|
      if @random_exam.save
        format.html { redirect_to @random_exam, notice: 'Random exam was successfully created.' }
        format.json { render :show, status: :created, location: @random_exam }
      else
        format.html { render :new }
        format.json { render json: @random_exam.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /random_exams/1
  # PATCH/PUT /random_exams/1.json
  def update
    respond_to do |format|
      if @random_exam.update(random_exam_params)
        format.html { redirect_to @random_exam, notice: 'Random exam was successfully updated.' }
        format.json { render :show, status: :ok, location: @random_exam }
      else
        format.html { render :edit }
        format.json { render json: @random_exam.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /random_exams/1
  # DELETE /random_exams/1.json
  def destroy
    @random_exam.destroy
    respond_to do |format|
      format.html { redirect_to random_exams_url, notice: 'Random exam was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_random_exam
      @random_exam = RandomExam.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def random_exam_params
      params.require(:random_exam).permit(
        :name,
        random_exam_sections_attributes: [
          :id,
          :selected,
          :section_id,
          :questions_number
        ]
      )
    end
end

app/controllers/sections_controller.rb
class SectionsController < ApplicationController
  before_action :set_section, only: [:show, :edit, :update, :destroy]

  # GET /sections
  # GET /sections.json
  def index
    @sections = Section.all
  end

  # GET /sections/1
  # GET /sections/1.json
  def show
  end

  # GET /sections/new
  def new
    @section = Section.new
  end

  # GET /sections/1/edit
  def edit
  end

  # POST /sections
  # POST /sections.json
  def create
    @section = Section.new(section_params)

    respond_to do |format|
      if @section.save
        format.html { redirect_to @section, notice: 'Section was successfully created.' }
        format.json { render :show, status: :created, location: @section }
      else
        format.html { render :new }
        format.json { render json: @section.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /sections/1
  # PATCH/PUT /sections/1.json
  def update
    respond_to do |format|
      if @section.update(section_params)
        format.html { redirect_to @section, notice: 'Section was successfully updated.' }
        format.json { render :show, status: :ok, location: @section }
      else
        format.html { render :edit }
        format.json { render json: @section.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /sections/1
  # DELETE /sections/1.json
  def destroy
    @section.destroy
    respond_to do |format|
      format.html { redirect_to sections_url, notice: 'Section was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_section
      @section = Section.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def section_params
      params.require(:section).permit(:name)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/random_exams_helper.rb
module RandomExamsHelper
end

app/helpers/sections_helper.rb
module SectionsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Randomexam</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/random_exams/_form.html.erb
<%= form_for(random_exam) do |f| %>
  <% if random_exam.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(random_exam.errors.count, "error") %> prohibited this random_exam from being saved:</h2>

      <ul>
      <% random_exam.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>

  <h4>Selected exams</h4>
  <%= f.fields_for :random_exam_sections do |b| %>
    <%= b.hidden_field :section_id %>
    <%= b.label :selected, b.object.section.name %>
    <%= b.check_box :selected, { checked: !b.object.id.blank? } %>
    <br>
    <%= b.label :question_numbers %>
    <%= b.text_field :questions_number %>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/random_exams/edit.html.erb
<h1>Editing Random Exam</h1>

<%= render 'form', random_exam: @random_exam %>

<%= link_to 'Show', @random_exam %> |
<%= link_to 'Back', random_exams_path %>

app/views/random_exams/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Random Exams</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @random_exams.each do |random_exam| %>
      <tr>
        <td><%= random_exam.name %></td>
        <td><%= link_to 'Show', random_exam %></td>
        <td><%= link_to 'Edit', edit_random_exam_path(random_exam) %></td>
        <td><%= link_to 'Destroy', random_exam, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Random Exam', new_random_exam_path %>

app/views/random_exams/new.html.erb
<h1>New Random Exam</h1>

<%= render 'form', random_exam: @random_exam %>

<%= link_to 'Back', random_exams_path %>

app/views/random_exams/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @random_exam.name %>
</p>

<%= link_to 'Edit', edit_random_exam_path(@random_exam) %> |
<%= link_to 'Back', random_exams_path %>

app/views/sections/_form.html.erb
<%= form_for(section) do |f| %>
  <% if section.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(section.errors.count, "error") %> prohibited this section from being saved:</h2>

      <ul>
      <% section.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/sections/edit.html.erb
<h1>Editing Section</h1>

<%= render 'form', section: @section %>

<%= link_to 'Show', @section %> |
<%= link_to 'Back', sections_path %>

app/views/sections/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Sections</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @sections.each do |section| %>
      <tr>
        <td><%= section.name %></td>
        <td><%= link_to 'Show', section %></td>
        <td><%= link_to 'Edit', edit_section_path(section) %></td>
        <td><%= link_to 'Destroy', section, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Section', new_section_path %>

app/views/sections/new.html.erb
<h1>New Section</h1>

<%= render 'form', section: @section %>

<%= link_to 'Back', sections_path %>

app/views/sections/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @section.name %>
</p>

<%= link_to 'Edit', edit_section_path(@section) %> |
<%= link_to 'Back', sections_path %>